.PHONY: clean All

All:
	@echo "----------Building project:[ CppTicTacToeGame - Debug ]----------"
	@cd "CppTicTacToeGame" && "$(MAKE)" -f  "CppTicTacToeGame.mk"
clean:
	@echo "----------Cleaning project:[ CppTicTacToeGame - Debug ]----------"
	@cd "CppTicTacToeGame" && "$(MAKE)" -f  "CppTicTacToeGame.mk" clean
