.PHONY: clean All

All:
	@echo "----------Building project:[ GameProject - Debug ]----------"
	@cd "GameProject" && "$(MAKE)" -f  "GameProject.mk"
clean:
	@echo "----------Cleaning project:[ GameProject - Debug ]----------"
	@cd "GameProject" && "$(MAKE)" -f  "GameProject.mk" clean
